name: deployReactFastAPI 
 
'on': 
  workflow_call: null 
  workflow_dispatch: null 
  push: 
    branches: 
      - master 
jobs: 
  DeployFastAPI: 
    name: Deploying FastAPI 
    runs-on: ubuntu-latest 
    steps: 
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: push to ECR
        run: | 
          ls
          docker build -t reactfastapi .
          docker tag reactfastapi:latest 428264194238.dkr.ecr.eu-north-1.amazonaws.com/reactfastapi:latest
          docker push 428264194238.dkr.ecr.eu-north-1.amazonaws.com/reactfastapi:latest
      - name: Connect to instance and deploy
        env: 
          SSH_KEY: ${{ secrets.KEY_SSH_PEM }} 
          HOST_NAME: ${{ secrets.BACK_HOST }}
          USERNAME: ${{ secrets.BACK_USERNAME }}
        run: |
          echo $SSH_KEY | tr ' ' '\n' | base64 --decode > key1.pem
          chmod 400 key1.pem
          ssh -o StrictHostKeyChecking=no -i "key1.pem" $USERNAME@$HOST_NAME './deploy.sh'
  DeployReact:  
    name: Deploying React 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: ReactDeploy 
        env: 
          SSH_KEY: ${{secrets.FASTAPI_KEY_SSH}} 
        run: | 
          echo $SSH_KEY | tr ' ' '\n' | base64 --decode > key1.pem 
          chmod 400 key1.pem 
          ssh -o StrictHostKeyChecking=no -i "key1.pem" ubuntu@ec2-51-20-60-12.eu-north-1.compute.amazonaws.com 'll'